### ISSUE TITLE
caproto server issue

### ISSUE THREAD

**Issue by vstadnytskyi** [vstadnytskyi/caproto-sandbox#3] opened 2019-10-08 21:33 UTC
I have two test server:
1) one PV [camera server](https://github.com/vstadnytskyi/caproto-sandbox/blob/master/caproto_sandbox/io_camera_server.py)
2) several PVs [io_device server](https://github.com/vstadnytskyi/caproto-sandbox/blob/master/caproto_sandbox/io_device_server.py) 
   I have made even[ simpler server with multiple PVs](https://github.com/vstadnytskyi/caproto-sandbox/blob/master/caproto_sandbox/io_device_server_one_thread.py) and still have the same problem

Both servers generate an image 3960,3960 with float64 ranging between 0 and 255.

I am trying to retrieve the image and print: actual array, array.shape,array.max(),array.mean()

Here is the [client](https://github.com/vstadnytskyi/caproto-sandbox/blob/master/caproto_sandbox/io_device_client_simple.py) 

And here are relevant pieces of the code. The full code check in links above.
``` python
image = epics.PV(pvname = default_prefix+'image', connection_timeout = 20)
def pyepics_for_loop():
    for i in range(4):
        img = image.get(timeout = 20)
        print(img,img.shape,img.max(),img.mean(),t1.get(),t2.get())
        sleep(1)

ctx = Context()
ca_img = ctx.get_pvs(default_prefix+'image')
def caproto_for_loop():
    for i in range(4):
        img = ca_img.read().data
        print(img,img.shape,img.max(),img.mean(),ca_t2.read().data[0])
        sleep(1)
```

It works well with the camera server
``` shell
In [1]: run caproto_sandbox/io_device_client_simple.py

In [2]: default_prefix
Out[2]: 'camera:'

In [3]: caproto_for_loop()

[179. 144. 167. ... 183. 177. 237.] (15681600,) 255.0 127.49332746658504
[211. 218. 249. ...  86. 102. 245.] (15681600,) 255.0 127.48166220283645
[ 77. 131.  72. ...   5. 189.  63.] (15681600,) 255.0 127.48323914651566
[135. 116. 222. ...  22. 126. 156.] (15681600,) 255.0 127.51444514590348

In [4]: pyepics_for_loop()
[ 16. 131. 169. ...  50. 169. 128.] (15681600,) 255.0 127.48961655698398
[  7. 139. 180. ... 253. 210.  83.] (15681600,) 255.0 127.4769012090603
[109. 156. 108. ... 127. 194.  67.] (15681600,) 255.0 127.49470283644526
[115. 164. 119. ... 227. 127. 214.] (15681600,) 255.0 127.4787924063871
```

The pyepics client fails to get data from the caproto "io_device" server. The max value in the array appears to be close to the timestamp.
``` shell
In [2]: run caproto_sandbox/io_device_client_simple.py

In [3]: default_prefix

Out[3]: 'io_device:'

In [4]: caproto_for_loop()
[ 75. 201. 122. ...  84. 163. 116.] (15681600,) 255.0 127.49252474237322
[191.  80. 253. ... 200. 251. 105.] (15681600,) 255.0 127.51174880114274
[ 25. 108. 146. ... 235. 125. 251.] (15681600,) 255.0 127.51386178706254
[ 60.  93. 240. ... 221.  98. 159.] (15681600,) 255.0 127.51358974849505

In [5]: pyepics_for_loop()
CAC: Undecipherable TCP message ( bad response type 16412 ) from myserver.gov:5064
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "myserver.gov:5064"
    Source File: ../cac.cpp line 1237
    Current Time: Tue Oct 08 2019 17:29:11.768520171
..................................................................
[115. 112. 216. ... 182. 169. 119.] (15681600,) 1570570166.1864076 327.79232126943043
[ 47. 198.  19. ... 124. 181. 190.] (15681600,) 255.0 127.54112769105194
CAC: Undecipherable TCP message ( bad response type 16468 ) from myserver.gov:5064
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "myserver.gov:5064"
    Source File: ../cac.cpp line 1237
    Current Time: Tue Oct 08 2019 17:29:20.073010817
..................................................................
[234. 188.  57. ... 177.  56.  68.] (15681600,) 1570570175.0612175 327.81672102381924
[157. 103.   4. ...  40.   2. 224.] (15681600,) 255.0 127.49858777165595
```

**Comment by vstadnytskyi** [comment] 2019-10-08 22:06
<img width="835" alt="image" src="https://user-images.githubusercontent.com/29989124/66436899-56dc1000-e9f6-11e9-8b2c-f828319e8924.png">

**Comment by vstadnytskyi** [comment] 2019-10-08 22:11
It is all good when I have stripped of other PV updates.

this works
 ```
       while True:
            value = await queue.async_get()
            #if 't1' in list(value.keys()):
            #    await self.t1.write(value['t1'])
            if 'image' in list(value.keys()):
                await self.image.write(value['image'])
            #if 't2' in list(value.keys()):
            #    await self.t2.write(value['t2'])
```
this doesn't
```
 while True:
            value = await queue.async_get()
            if 't1' in list(value.keys()):
                await self.t1.write(value['t1'])
            if 'image' in list(value.keys()):
                await self.image.write(value['image'])
            if 't2' in list(value.keys()):
                await self.t2.write(value['t2'])
```
with the commented version I was able to get data in both way.
```
In [5]: caproto_for_loop()
img,img.shape,img.max(),img.mean(),ca_t2.read().data[0]
[186.  26.  72. ... 143.  97.  53.] (15681600,) 255.0 127.49675300989695 2.0
[197.  53.  22. ...  17. 136. 120.] (15681600,) 255.0 127.49888601928374 2.0
[ 41. 143.  66. ... 220.  31.   9.] (15681600,) 255.0 127.51537623711866 2.0
[233. 186. 156. ... 135.  77. 210.] (15681600,) 255.0 127.52278504744415 2.0

In [6]: pyepics_for_loop()
img,img.shape,img.max(),img.mean(),t1.get(),t2.get()
[183.  64.  46. ...  29. 121.  96.] (15681600,) 255.0 127.52762664524028 2.0 2.0
[219. 250.  18. ... 112. 153. 157.] (15681600,) 255.0 127.49016216457504 2.0 2.0
[133.  77. 201. ...  30. 166.  13.] (15681600,) 255.0 127.50052928272625 2.0 2.0
[ 40.  65. 240. ... 213.   8. 215.] (15681600,) 255.0 127.4964534868891 2.0 2.0

In [7]: default_prefix
Out[7]: 'io_device_single:'

In [8]:
```

**Comment by tacaswell** [comment] 2019-10-09 00:09
Interesting.

The error in the server is not unreasonable, but should be better handled, if the client panicked and killed the socket part of the way through.

This exception looks like it is from the guard around the jump table so the command should be ~20 but you are getting 16468!

Going to poke at this a bit, but does it work with pyepics if you don't use the caproto client first in the same process?  I am worried that they are somehow sharing the same network buffers and then reads get out of sync...

**Comment by vstadnytskyi** [comment] 2019-10-09 02:17
@tacaswell 
> Interesting.
> 
> The error in the server is not unreasonable, but should be better handled, if the client panicked and killed the socket part of the way through.
> 
> This exception looks like it is from the guard around the jump table so the command should be ~20 but you are getting 16468!

What does this 16468 mean?

> 
> Going to poke at this a bit, but does it work with pyepics if you don't use the caproto client first in the same process? I am worried that they are somehow sharing the same network buffers and then reads get out of sync...

Here I have stripped the caproto part and ran just pyepics.

``` python
from logging import debug,warn,info,error
import epics
from time import time,sleep
from _thread import start_new_thread
from pdb import pm
import epics
from numpy import nan
default_prefix='io_device_single:'

image = epics.PV(pvname = default_prefix+'image', connection_timeout = 20, verbose = False)
t1 = epics.PV(pvname = default_prefix+'t1', verbose = False)
t2 = epics.PV(pvname = default_prefix+'t2', verbose = False)


def pyepics_for_loop():
    print('img,img.shape,img.max(),img.mean(),t1.get(),t2.get()')
    for i in range(4):
        img = image.get(timeout = 20)
        print(img,img.shape,img.max(),img.mean(),t1.get(),t2.get())
        sleep(1)

pyepics_for_loop()
```

and if I run it 
``` shell
$ python3 caproto_sandbox/io_device_client_simple.py
img,img.shape,img.max(),img.mean(),t1.get(),t2.get()
[216. 156.  24. ...  16. 213. 203.] (15681600,) 255.0 127.49727578818488 1570586387.229585 1570586387.646207
[ 32. 255. 246. ... 145.  17. 119.] (15681600,) 255.0 -9.808168266947858e+19 1570586388.706607 1570586388.828989
CAC: Undecipherable TCP message ( bad response type 16480 ) from 10.225.185.149:5064
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "10.225.185.149:5064"
    Source File: ../cac.cpp line 1237
    Current Time: Tue Oct 08 2019 21:59:51.858438265

..................................................................
Traceback (most recent call last):
  File "caproto_sandbox/io_device_client_simple.py", line 37, in <module>
    pyepics_for_loop()
  File "caproto_sandbox/io_device_client_simple.py", line 27, in pyepics_for_loop
    img = image.get(timeout = 20)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/pv.py", line 484, in get
    use_monitor=use_monitor)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/pv.py", line 562, in get_with_metadata
    as_numpy=as_numpy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/ca.py", line 620, in wrapper
    return fcn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/ca.py", line 1375, in get_with_metadata
    as_numpy=as_numpy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/ca.py", line 620, in wrapper
    return fcn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/ca.py", line 1516, in get_complete_with_metadata
    raise get_failure_reason
epics.ca.ChannelAccessGetFailure: Get failed; status code: 192
```

The servers shell prints. We do we have 3 clients connected and 2 disconnected? what happened with one of them? Is that we I have an error?
 
``` shell
[I 21:59:46.826          common:  967] Connected to new client at 10.225.185.149:50709 (total: 3).
[I 21:59:51.859          common:  982] Disconnected from client at 10.225.185.149:50709 (total: 2).
```

**Comment by vstadnytskyi** [comment] 2019-10-09 02:31
Few things I have discovered. 
1) my original code was updating .image PV more frequent than it takes to transfer it. I have throttled down the server. The problem didn't go away though.
2) I have plotted the way how my array looks if i got this bogus value in it. (see below)
3) the bogus value is local time stamp. Somehow it leaks in. I have modified my code to publish a different value instead of time.time()

modifications:
```
t = time()/10e4
t = time()/10e5
```

result of the new code and the bogus value became 1570.5881816385852 which is 10e5 time smaller. So PV .t1 got mixed into PV .image.
``` python
$ python3 caproto_sandbox/io_device_client_simple.py
img,img.shape,img.max(),img.mean(),t1.get(),t2.get()
[ 40.  21.  58. ... 168. 110. 134.] (15681600,) 255.0 127.51687353331293 1570.588163122984 15705.88161120758
[ 69. 217.  86. ...   7. 165.   3.] (15681600,) 255.0 127.47806014692378 1570.588169350563 15705.8816734878
[233.  38. 240. ... 238. 194. 209.] (15681600,) 255.0 127.52687015355576 1570.5881754929437 15705.881734871791
[214.  15. 238. ... 188. 191.  48.] (15681600,) 1570.5881816385852 127.51902819789954 1570.5881754929437 15705.881796354517
CAC: Undecipherable TCP message ( bad response type 16467 ) from 10.225.185.149:5064
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "10.225.185.149:5064"
    Source File: ../cac.cpp line 1237
    Current Time: Tue Oct 08 2019 22:30:09.203968772
..................................................................
Traceback (most recent call last):

  File "caproto_sandbox/io_device_client_simple.py", line 42, in <module>
    pyepics_for_loop()
  File "caproto_sandbox/io_device_client_simple.py", line 28, in pyepics_for_loop
    img = image.get(timeout = 20)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/pv.py", line 484, in get
    use_monitor=use_monitor)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/pv.py", line 562, in get_with_metadata
    as_numpy=as_numpy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/ca.py", line 620, in wrapper
    return fcn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/ca.py", line 1375, in get_with_metadata
    as_numpy=as_numpy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/epics/ca.py", line 620, in wrapper
    return fcn(*args, **kwds)
..................................................................
```
<img width="752" alt="image" src="https://user-images.githubusercontent.com/29989124/66447110-2f4b6e80-ea1b-11e9-8789-97880fb9633c.png">


<img width="752" alt="image" src="https://user-images.githubusercontent.com/29989124/66446672-84868080-ea19-11e9-9d57-7148a08a01de.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/29989124/66446741-d3341a80-ea19-11e9-9cf0-44cf9cf8621f.png">

**Comment by tacaswell** [comment] 2019-10-09 11:39
The number is the "command id" which is basicallly an enum that CA uses to know how to interpret the rest of the bytes (see https://github.com/caproto/caproto/blob/master/caproto/_commands.py).

This is a server bug, the reason we see this in pyepics and not caproto is that we do not auto-monitor PVs, if you add callbacks you will see this (in a slightly different manner) with the caproto client.  I think the issue is that the event is being generated and shoved onto the socket in the middle of writing the read response.  Epics is just looking for a binary run of data so it just reads that as event response as some pixels (we must be getting lucky on byte alignment).  Once the image is "done", libca that reads the next chunk of bytes off the socket which _should_ be the AddEvent command, but is instead the end of your image which is going to be nonsense so you get the warning.

**Comment by vstadnytskyi** [comment] 2019-10-09 12:32
@tacaswell 
I thought about subscription(auto-monitoring) but the default value "auto_monitor" is None when you create a PV with pyepics. I assumed it is not going to auto-monitor. However, if I have verbose = True, I see PVs .t1 and .t2 been updated but not .image

```python
import epics
help(epics.PV)
class PV(builtins.object) 
 PV(pvname, callback=None,
 form='time', 
 verbose=False,
 auto_monitor=None,
 count=None, 
 connection_callback=None, 
 connection_timeout=None,
 access_callback=None)
```

**Comment by tacaswell** [comment] 2019-10-09 16:24
Fixed by https://github.com/caproto/caproto/pull/529

**Comment by vstadnytskyi** [comment] 2019-10-09 17:50
#close

**Closed** 2019-10-09 17:50 UTC
Labels: help wanted
